services:
  - type: web
    name: bot-telegram-consulta
    runtime: docker
    repo: https://github.com/lu3tak-coder/bot-telegram-consulta.git
    branch: main
    autoDeployTrigger: commit
    plan: free
    region: oregon
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: KEEP_ALIVE_URL
        value: https://bot-telegram-consulta.onrender.com/
      - key: KEEP_ALIVE_INTERVAL
        value: 300
