services:
  - type: web
    name: bot-telegram-consulta
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: 1
